/**
 * A map from common armature rig names to VRM Humanoid bone names
 */
export const armatureVRMRigMap = {
    Hips: "hips",
    Spine: "spine",
    Spine1: "spine",
    Spine2: "chest",
    Spine3: "upperChest",
    Neck: "neck",
    Head: "head",
    LeftShoulder: "leftShoulder",
    LeftArm: "leftUpperArm",
    LeftForeArm: "leftLowerArm",
    LeftHand: "leftHand",
    LeftHandThumb1: "leftThumbProximal",
    LeftHandThumb2: "leftThumbIntermediate",
    LeftHandThumb3: "leftThumbDistal",
    LeftHandIndex1: "leftIndexProximal",
    LeftHandIndex2: "leftIndexIntermediate",
    LeftHandIndex3: "leftIndexDistal",
    LeftHandMiddle1: "leftMiddleProximal",
    LeftHandMiddle2: "leftMiddleIntermediate",
    LeftHandMiddle3: "leftMiddleDistal",
    LeftHandRing1: "leftRingProximal",
    LeftHandRing2: "leftRingIntermediate",
    LeftHandRing3: "leftRingDistal",
    LeftHandPinky1: "leftLittleProximal",
    LeftHandPinky2: "leftLittleIntermediate",
    LeftHandPinky3: "leftLittleDistal",
    RightShoulder: "rightShoulder",
    RightArm: "rightUpperArm",
    RightForeArm: "rightLowerArm",
    RightHand: "rightHand",
    RightHandThumb1: "rightThumbProximal",
    RightHandThumb2: "rightThumbIntermediate",
    RightHandThumb3: "rightThumbDistal",
    RightHandIndex1: "rightIndexProximal",
    RightHandIndex2: "rightIndexIntermediate",
    RightHandIndex3: "rightIndexDistal",
    RightHandMiddle1: "rightMiddleProximal",
    RightHandMiddle2: "rightMiddleIntermediate",
    RightHandMiddle3: "rightMiddleDistal",
    RightHandRing1: "rightRingProximal",
    RightHandRing2: "rightRingIntermediate",
    RightHandRing3: "rightRingDistal",
    RightHandPinky1: "rightLittleProximal",
    RightHandPinky2: "rightLittleIntermediate",
    RightHandPinky3: "rightLittleDistal",
    LeftUpLeg: "leftUpperLeg",
    LeftLeg: "leftLowerLeg",
    LeftFoot: "leftFoot",
    LeftToeBase: "leftToes",
    RightUpLeg: "rightUpperLeg",
    RightLeg: "rightLowerLeg",
    RightFoot: "rightFoot",
    RightToeBase: "rightToes",
    HeadTop_End: null, // Optional, not mapped in VRM by default
  };
  